import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import {
  Alert,
  FlatList,
  Pressable,
  RefreshControl,
  SafeAreaView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from "react-native";
import { useAuth } from "../../contexts/AuthContext";
import { useThemeColor } from "../../hooks/useThemeColor";
import { apiClient, ProductItem } from "../../utils/api";
import { navigateBackGently, NavigationPresets } from "../../utils/navigation";

interface ShoppingItem {
  id: string;
  name: string;
  category: string;
  quantity?: number;
  unit?: string;
  completed: boolean;
  addedAt: Date;
  source: "auto" | "manual"; // Track if item was auto-generated or manually added
  productId?: string; // Link to the product that generated this item
}

export default function ShoppingList() {
  const { user } = useAuth();
  const router = useRouter();
  const [items, setItems] = useState<ShoppingItem[]>([]);
  const [products, setProducts] = useState<ProductItem[]>([]);
  const [newItemName, setNewItemName] = useState("");
  const [isAddingItem, setIsAddingItem] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [isRefreshing, setIsRefreshing] = useState(false);

  // Theme colors
  const backgroundColor = useThemeColor({}, "background");
  const cardBackground = useThemeColor({}, "cardBackground");
  const textColor = useThemeColor({}, "text");
  const subtitleColor = useThemeColor({}, "subtitleText");
  const borderColor = useThemeColor({}, "borderColor");
  const tintColor = useThemeColor({}, "tint");
  const successColor = useThemeColor({}, "successColor");
  const warningColor = useThemeColor({}, "warningColor");

  useEffect(() => {
    loadInitialData();
  }, []);

  const loadInitialData = async () => {
    setIsLoading(true);
    await Promise.all([fetchProducts(), loadShoppingListFromStorage()]);
    setIsLoading(false);
  };

  const fetchProducts = async () => {
    try {
      const response = await apiClient.getProducts();
      setProducts(response.data);
      generateAutoItems(response.data);
    } catch (error) {
      console.error("Failed to fetch products:", error);
    }
  };

  const loadShoppingListFromStorage = async () => {
    // In a real app, you'd load from AsyncStorage
    // For now, we'll just initialize with empty array
    setItems([]);
  };

  const generateAutoItems = (productList: ProductItem[]) => {
    const today = new Date();
    const sevenDaysFromNow = new Date(
      today.getTime() + 7 * 24 * 60 * 60 * 1000
    );

    // Find items that are expiring soon or expired
    const expiringItems = productList.filter((product) => {
      if (!product.expected_expiry || product.status !== "active") return false;
      const expiryDate = new Date(product.expected_expiry);
      return expiryDate <= sevenDaysFromNow;
    });

    // Generate shopping list items for expiring products
    const autoGeneratedItems: ShoppingItem[] = expiringItems.map((product) => ({
      id: `auto-${product.id}`,
      name: product.name,
      category: getCategoryDisplayName(product.category.name),
      quantity: product.quantity || 1,
      unit: product.unit || "item",
      completed: false,
      addedAt: new Date(),
      source: "auto",
      productId: product.id,
    }));

    // Merge with existing manual items, avoiding duplicates
    setItems((prevItems) => {
      const manualItems = prevItems.filter((item) => item.source === "manual");
      const existingAutoIds = new Set(
        prevItems
          .filter((item) => item.source === "auto")
          .map((item) => item.productId)
      );
      const newAutoItems = autoGeneratedItems.filter(
        (item) => !existingAutoIds.has(item.productId)
      );

      return [...manualItems, ...newAutoItems].sort((a, b) => {
        // Sort auto items first, then by date
        if (a.source !== b.source) {
          return a.source === "auto" ? -1 : 1;
        }
        return b.addedAt.getTime() - a.addedAt.getTime();
      });
    });
  };

  const getCategoryDisplayName = (categoryId: string): string => {
    const categoryMap: { [key: string]: string } = {
      pantry: "Pantry",
      fresh: "Fresh Produce",
      personal: "Personal Care",
      beauty: "Beauty",
      laundry: "Laundry",
      household: "Household",
      dairy: "Dairy & Eggs",
      "meat-seafood": "Meat & Seafood",
      frozen: "Frozen Foods",
      beverages: "Beverages",
      snacks: "Snacks",
      "health-beauty": "Health & Beauty",
    };
    return categoryMap[categoryId] || categoryId;
  };

  const handleRefresh = useCallback(async () => {
    setIsRefreshing(true);
    await fetchProducts();
    setIsRefreshing(false);
  }, []);

  const addItem = () => {
    if (!newItemName.trim()) {
      Alert.alert("Error", "Please enter an item name");
      return;
    }

    const newItem: ShoppingItem = {
      id: Date.now().toString(),
      name: newItemName.trim(),
      category: "General",
      completed: false,
      addedAt: new Date(),
      source: "manual",
    };

    setItems([newItem, ...items]);
    setNewItemName("");
    setIsAddingItem(false);
  };

  const toggleItem = (id: string) => {
    setItems(
      items.map((item) =>
        item.id === id ? { ...item, completed: !item.completed } : item
      )
    );
  };

  const deleteItem = (id: string) => {
    setItems(items.filter((item) => item.id !== id));
  };

  const clearCompleted = () => {
    Alert.alert(
      "Clear Completed Items",
      "Are you sure you want to remove all completed items?",
      [
        { text: "Cancel", style: "cancel" },
        {
          text: "Clear",
          style: "destructive",
          onPress: () => setItems(items.filter((item) => !item.completed)),
        },
      ]
    );
  };

  const clearAutoGenerated = () => {
    Alert.alert(
      "Clear Auto-Generated Items",
      "This will remove all items that were automatically added from your expiring products. Manual items will remain.",
      [
        { text: "Cancel", style: "cancel" },
        {
          text: "Clear",
          style: "destructive",
          onPress: () =>
            setItems(items.filter((item) => item.source === "manual")),
        },
      ]
    );
  };

  const regenerateShoppingList = async () => {
    Alert.alert(
      "Regenerate Shopping List",
      "This will refresh the auto-generated items based on your current expiring products.",
      [
        { text: "Cancel", style: "cancel" },
        {
          text: "Regenerate",
          onPress: async () => {
            setIsRefreshing(true);
            await fetchProducts();
            setIsRefreshing(false);
          },
        },
      ]
    );
  };

  const renderItem = ({ item }: { item: ShoppingItem }) => (
    <View
      style={[
        styles.itemCard,
        { backgroundColor: cardBackground, borderColor },
        item.completed && styles.completedItem,
      ]}
    >
      <Pressable style={styles.itemContent} onPress={() => toggleItem(item.id)}>
        <View style={styles.checkboxContainer}>
          <Ionicons
            name={item.completed ? "checkmark-circle" : "ellipse-outline"}
            size={24}
            color={item.completed ? successColor : subtitleColor}
          />
        </View>
        <View style={styles.itemDetails}>
          <View style={styles.itemHeader}>
            <Text
              style={[
                styles.itemName,
                { color: textColor },
                item.completed && {
                  textDecorationLine: "line-through",
                  color: subtitleColor,
                },
              ]}
            >
              {item.name}
            </Text>
            {item.source === "auto" && (
              <View
                style={[
                  styles.autoTag,
                  {
                    backgroundColor: warningColor + "20",
                    borderColor: warningColor,
                  },
                ]}
              >
                <Ionicons name="flash" size={12} color={warningColor} />
                <Text style={[styles.autoTagText, { color: warningColor }]}>
                  Auto
                </Text>
              </View>
            )}
          </View>
          <Text style={[styles.itemCategory, { color: subtitleColor }]}>
            {item.category}
            {item.quantity && item.unit && ` • ${item.quantity} ${item.unit}`}
          </Text>
          {item.source === "auto" && (
            <Text style={[styles.autoDescription, { color: subtitleColor }]}>
              Added because item is expiring soon
            </Text>
          )}
        </View>
      </Pressable>
      <Pressable
        style={styles.deleteButton}
        onPress={() => deleteItem(item.id)}
      >
        <Ionicons name="trash-outline" size={20} color={subtitleColor} />
      </Pressable>
    </View>
  );

  const completedCount = items.filter((item) => item.completed).length;
  const totalCount = items.length;
  const autoCount = items.filter((item) => item.source === "auto").length;
  const manualCount = items.filter((item) => item.source === "manual").length;

  if (isLoading) {
    return (
      <SafeAreaView style={[styles.container, { backgroundColor }]}>
        <View style={styles.centerContent}>
          <Text style={{ color: textColor }}>Loading shopping list...</Text>
        </View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={[styles.container, { backgroundColor }]}>
      {/* Header */}
      <View
        style={[
          styles.header,
          { backgroundColor: cardBackground, borderBottomColor: borderColor },
        ]}
      >
        <Pressable
          style={styles.backButton}
          onPress={() => navigateBackGently(NavigationPresets.gentle)}
          hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}
        >
          <Ionicons name="arrow-back" size={24} color={textColor} />
        </Pressable>
        
        <View style={styles.headerContent}>
          <Text style={[styles.headerTitle, { color: textColor }]}>
            Shopping List
          </Text>
          <Text style={[styles.headerSubtitle, { color: subtitleColor }]}>
            {totalCount > 0
              ? `${completedCount}/${totalCount} completed`
              : "No items yet"}
          </Text>
          {autoCount > 0 && (
            <Text
              style={[
                styles.headerSubtitle,
                { color: warningColor, fontSize: 12 },
              ]}
            >
              {autoCount} auto-generated • {manualCount} manual
            </Text>
          )}
        </View>
        <View style={styles.headerActions}>
          {autoCount > 0 && (
            <Pressable
              onPress={regenerateShoppingList}
              style={[styles.headerActionButton, { marginRight: 8 }]}
            >
              <Ionicons name="refresh" size={16} color={tintColor} />
            </Pressable>
          )}
          {completedCount > 0 && (
            <Pressable
              onPress={clearCompleted}
              style={styles.headerActionButton}
            >
              <Ionicons name="checkmark-done" size={16} color={tintColor} />
            </Pressable>
          )}
          {autoCount > 0 && (
            <Pressable
              onPress={clearAutoGenerated}
              style={[styles.headerActionButton, { marginLeft: 8 }]}
            >
              <Ionicons name="flash-off" size={16} color={subtitleColor} />
            </Pressable>
          )}
        </View>
      </View>

      {/* Add Item Input */}
      {isAddingItem ? (
        <View
          style={[styles.addItemContainer, { backgroundColor: cardBackground }]}
        >
          <TextInput
            style={[styles.addItemInput, { color: textColor, borderColor }]}
            placeholder="Enter item name..."
            placeholderTextColor={subtitleColor}
            value={newItemName}
            onChangeText={setNewItemName}
            autoFocus
            onSubmitEditing={addItem}
            returnKeyType="done"
          />
          <View style={styles.addItemActions}>
            <Pressable
              style={[styles.actionButton, { backgroundColor: borderColor }]}
              onPress={() => {
                setIsAddingItem(false);
                setNewItemName("");
              }}
            >
              <Text style={[styles.actionButtonText, { color: textColor }]}>
                Cancel
              </Text>
            </Pressable>
            <Pressable
              style={[styles.actionButton, { backgroundColor: tintColor }]}
              onPress={addItem}
            >
              <Text style={[styles.actionButtonText, { color: "#fff" }]}>
                Add
              </Text>
            </Pressable>
          </View>
        </View>
      ) : (
        <Pressable
          style={[
            styles.addButton,
            { backgroundColor: cardBackground, borderColor },
          ]}
          onPress={() => setIsAddingItem(true)}
        >
          <Ionicons name="add" size={24} color={tintColor} />
          <Text style={[styles.addButtonText, { color: tintColor }]}>
            Add Item
          </Text>
        </Pressable>
      )}

      {/* Shopping List */}
      {items.length === 0 ? (
        <View style={styles.emptyState}>
          <Ionicons name="list-outline" size={64} color={subtitleColor} />
          <Text style={[styles.emptyTitle, { color: textColor }]}>
            Your Shopping List is Empty
          </Text>
          <Text style={[styles.emptySubtitle, { color: subtitleColor }]}>
            {products.length === 0
              ? "Add some products to track and YourButler will automatically suggest items when they're expiring"
              : "Add items manually or wait for YourButler to suggest items when they're expiring"}
          </Text>
          {products.length > 0 && (
            <Pressable
              style={[
                styles.emptyButton,
                { backgroundColor: tintColor, marginTop: 16 },
              ]}
              onPress={regenerateShoppingList}
            >
              <Ionicons name="refresh" size={20} color="#fff" />
              <Text style={styles.emptyButtonText}>
                Check for Expiring Items
              </Text>
            </Pressable>
          )}
        </View>
      ) : (
        <FlatList
          data={items}
          keyExtractor={(item) => item.id}
          renderItem={renderItem}
          style={styles.itemsList}
          contentContainerStyle={styles.itemsListContent}
          showsVerticalScrollIndicator={false}
          refreshControl={
            <RefreshControl
              refreshing={isRefreshing}
              onRefresh={handleRefresh}
              tintColor={tintColor}
            />
          }
        />
      )}
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  centerContent: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 40,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
  },
  backButton: {
    padding: 8,
    borderRadius: 8,
    marginRight: 12,
  },
  headerContent: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "700",
  },
  headerSubtitle: {
    fontSize: 14,
    marginTop: 2,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
  },
  headerActionButton: {
    padding: 8,
    borderRadius: 20,
  },
  clearButton: {
    padding: 8,
  },
  clearButtonText: {
    fontSize: 14,
    fontWeight: "600",
  },
  // Add Item
  addButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 20,
    marginTop: 16,
    padding: 16,
    borderRadius: 12,
    borderWidth: 2,
    borderStyle: "dashed",
  },
  addButtonText: {
    fontSize: 16,
    fontWeight: "600",
    marginLeft: 8,
  },
  addItemContainer: {
    marginHorizontal: 20,
    marginTop: 16,
    padding: 16,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  addItemInput: {
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 16,
    marginBottom: 12,
  },
  addItemActions: {
    flexDirection: "row",
    gap: 8,
  },
  actionButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: "center",
  },
  actionButtonText: {
    fontSize: 14,
    fontWeight: "600",
  },
  // Items List
  itemsList: {
    flex: 1,
    paddingHorizontal: 20,
  },
  itemsListContent: {
    paddingTop: 16,
    paddingBottom: 100,
  },
  itemCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    marginBottom: 8,
    borderRadius: 12,
    borderWidth: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  completedItem: {
    opacity: 0.6,
  },
  itemContent: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  checkboxContainer: {
    marginRight: 12,
  },
  itemDetails: {
    flex: 1,
  },
  itemHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  itemName: {
    fontSize: 16,
    fontWeight: "500",
    flex: 1,
  },
  autoTag: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
  },
  autoTagText: {
    fontSize: 10,
    fontWeight: "600",
  },
  itemCategory: {
    fontSize: 14,
    marginBottom: 2,
  },
  autoDescription: {
    fontSize: 12,
    fontStyle: "italic",
  },
  deleteButton: {
    padding: 8,
  },
  // Empty State
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 40,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "600",
    marginTop: 16,
    marginBottom: 8,
  },
  emptySubtitle: {
    fontSize: 16,
    textAlign: "center",
    lineHeight: 22,
  },
  emptyButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    gap: 8,
  },
  emptyButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
});
